name: Release

on:
  push:
    branches:
      - beta
      - master

permissions: {}

jobs:
  release:
    name: Publish & Deploy
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      # Don't run publish until we're ready for it
      # - name: Publish action
      #   run: yarn release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.SEEK_OSS_CI_NPM_TOKEN }}
